### ISSUE TITLE
Contact page gives post confirmation

### ISSUE THREAD

**Issue by ocassidydev** [The-Carbon-Crushers/greenways#41]
As a user, I want the contact page to give some post confirmation, so that I know my message has been sent.

## Requirements 

- Changed content on the page so that form becomes invisible when submitted 
- Content that pops up that confirms user has sent their message

## Tasks 

- [x] Make js script that manipulates DOM to make certain elements disappear and some appear when send message is clicked
- [x] Edit contact.html to contain hidden elements for telling the user they have sent their message

**Comment by dcsndevs** [comment]
Done!

**Comment by dcsndevs** [comment]
Done
